---
title: "STA4002HF - Data Science, Collaboration, and Communication (Fall 2017)"
output:
  html_document: default
  pdf_document: default
bibliography: syllab.bib
---

# Course Description

Students will gain experience with the data science process including: data collection; stating the question; data wrangling; data analysis; data interpretation; and communication by working on projects.  The projects will involve data collected by an organization (e.g., organization or scientist), using published data, or scraping web pages.  All projects will involve some type of collaboration or communication. Students are expected to be familiar with the application of basic statistical methods used for inference (e.g., general linear models), prediction (e.g., linear and logistic regression), and are comfortable with basic data analysis using a programming language such as R or Python.  Students will be expected to adopt a reproducible research workflow using tools such as R Markdown, R Notebook, or Jupyter Notebook. 

Class time will be a mixture of informal lectures, class discussions, meetings with collaborators, and student presentations.

This course will not cover specific "methods", nevertheless it's important that students are able to independently learn and apply unfamilar methods.

# Evaluation

All work will be graded on a scale from 1 to 4 (sometimes with pluses and minuses) where:


------------------------------------------------------------------------
Grade value   Description
-----------   ---------------------------------------------------------
1             Work does not meet expectations.

2             Work meets expectations minimally, possibly missing some.

3             Good work; meets all or most expectations.

4             Excellent work; exceeds expectations.
------------------------------------------------------------------------


Grades will almost always be 2 or 3 (1’s and 4’s are rare). Generally speaking, a 2 is a B, a 3 is an A, and a 4 is an A+.



-----------------------------------------
Project        Item              Value               
-------------- ----------------- -------- 
Project #1     Proposal          5%

               Draft report      5%               

               Final report      10%              
               
               Presentation      20%              
               on project #1
               
Project #2     Proposal          5%

               Draft report      5%               

               Final report      10%              
               
               Presentation      20%              
               on project #2

Participation  Attendance,       20%             
               participate in
               discussions, 
               prepare for class
-----------------------------------------


# Tentative Course Schedule

-------------------------------------------------------------------------------------------------------------
Class    Date     Description                             Reading                          Due
-----    -----    --------------------------------------  ------------------------------   -----------------
1        09-12    Introduction, data analysis case study  


2        09-19    Data Analysis, questions, web scraping, @peng2015art (1-3), @Leek1314
                  discuss ideas project #1
                  
                  
3        09-26    Exploratory data analysis,              @peng2015art (4),  
                  discuss ideas project #1                @donoho50years 


4        10-03    Models                                  @peng2015art (5)                 Project #1 proposal


6        10-10    Inference vs. prediction, discuss       @peng2015art (8), @breiman2001   Project #1 draft report
                  project #2


7        10-24    Project #1 presentations                                                 Project #1 report due, meet with 
                                                                                           collaborators by 10-27                                                               
                                                                                           
8        10-31    Project #1 presentations                                                 Project #2 proposals due


-        11-07    No class - Fall reading week


9        11-14    Project #2 check-in                     @googleflu


10       11-21    Project #2 check-in and                                                  Project #2 draft report
                  quick presentations


11       11-28    Project #2 presentations                          


12       12-5     Project #2 presentations                                                   Project #2 report due

-------------------------------------------------------------------------------------------------------------

# Reading References

\bibliography{syllab.bib}
